---
title: "05_taxonomic_classification"
author: "Justin Proctor"
format: html
editor: visual
---

## Workshop 4: Metagenome Function

### Step 5: Perform taxonomic classification with gtdbtk

make and cd checkm directory

``` bash
mkdir gtdbtk
cd gtdbtk
```

create a subfolder within the gtdbtk folder called genomes

``` bash
mkdir genomes
```

iterating over the list of topbins. For each of the topbins, I copied a file corresponding to that bin into the genomes folder.

step 1: get the while loop working

``` bash
while read bin;do echo $bin;done < ../checkm/bbd_topbins.txt
```

step 2: using echo bin to simply print the name of the bin.

Build the complete file path for each genome bin so downstream tools can locate the associated FASTA file. This is achieved by adding the parent directory before the bin name and the .fa extension after it.

``` bash
while read bin;do echo "../metabat/bins_bbd/${bin}.fa";done \< ../checkm/bbd_topbins.txt
```

step 3: had to manually move config_137 to metabat directory for step 4 to work

``` bash
cp checkm/bins_bbd/contig_137.fa metabat/bins_bbd/
```

step 4: perform the copy

``` bash
while read bin;do cp "../metabat/bins_bbd/${bin}.fa" genomes;done < ../checkm/bbd_topbins.txt
```

step 5: run the classification workflow via slurm job script run_gtdbtk.sh (code for it below. Note: changed mem to 40gb)

``` bash
#!/bin/bash
#SBATCH --time=60
#SBATCH --ntasks=2 --mem=40gb

echo "Starting gtdbtk in $(pwd) at $(date)"

shopt -s expand_aliases
alias gtdbtk='apptainer run -B /pvol:/pvol,/pvol/data/mg/gtdbtkdata/release207_v2/:/refdata /pvol/data/sif/gtdbtk.sif'

gtdbtk classify_wf -x fa --cpus 2 --genome_dir genomes --out_dir out --skip_ani_screen

echo "Finished gtdbtk in $(pwd) at $(date)"
```

step 6: submit job

``` bash
sbatch run_gtdbtk.sh
```
