---
title: "07_metabolic_pathways"
author: "Justin Proctor"
format: html
editor: visual
---

## Workshop 4: Metagenome Function

### Step 7: Infer metabolic pathways

make and cd minpath directory
``` bash
mkdir minpath
cd minpath
```

looking at the contig_137.tsv file for a single bin

``` bash
head ../prokka/contig_137/contig_137.tsv
```

General formatting

1\. transforming the tsv into a format that only keeps a unique ID for each gene and its EC number

2\. filter the output to only include lines with an EC number

3\. making the output tab separated and removing the header line

4\. change head to cat to include all genes

``` bash
head ../prokka/contig_137/contig_137.tsv | awk -F '\t' '{print $1,$5}'
head ../prokka/contig_137/contig_137.tsv | awk -F '\t' '$5{print $1,$5}'
head ../prokka/contig_137/contig_137.tsv | awk -F '\t' '$5{OFS="\t";print $1,$5}' | grep -v '^locus'
cat ../prokka/contig_137/contig_137.tsv | awk -F '\t' '$5{OFS="\t";print $1,$5}' | grep -v '^locus'
```

sending the output from above to a file so it can be used as an input to minpath

``` bash
cat ../prokka/contig_137/contig_137.tsv | awk -F '\t' '$5{OFS="\t";print $1,$5}' | grep -v '^locus' > contig_137.ec
```

run minpath on the file created above

``` bash
minpath -ec contig_137.ec -report contig_137.ec.report -details contig_137.ec.details
```

preparing minpath inputs for all bins

``` bash
while read bin;do 
  cat ../prokka/$bin/${bin}.tsv | awk -F '\t' '$5{printf("%s\t%s\n", $1,$5)}' | grep -v '^locus' > ${bin}.ec 
done < ../checkm/bbd_topbins.txt
```

running minpath on every bin

``` bash
while read bin;do 
  minpath -ec ${bin}.ec -report ${bin}.ec.report -details ${bin}.ec.details
done < ../checkm/bbd_topbins.txt
```

filtering the minpath outputs from above for pathways that includes Photosystem I and Photosystem II (essential components of photosynthesis that occur in light)

``` bash
grep 'PWY-101' *.ec.report
```

the filtered outputs:

contig_137.ec.report:path PWY-101 any n/a naive 1 minpath 0 fam0 4 fam-found 1 name photosynthesis light reactions

metabat.27.ec.report:path PWY-101 any n/a naive 1 minpath 1 fam0 4 fam-found 4 name photosynthesis light reactions

metabat.59.ec.report:path PWY-101 any n/a naive 1 minpath 0 fam0 4 fam-found 1 name photosynthesis light reactions

#### Question 4.1:

How many bins contain at least one gene from this pathway?

3 bins

Which bin has all of the genes (ie a complete pathway)?

1 bin: matabat.27

Cross referencing the above results with the output from gtdbtk to see the taxonomy of bins containing this same pathway

``` bash
grep 'contig_137' ../gtdbtk/out/gtdbtk.bac120.summary.tsv
grep 'metabat.27' ../gtdbtk/out/gtdbtk.bac120.summary.tsv
grep 'metabat.59' ../gtdbtk/out/gtdbtk.bac120.summary.tsv
```

filtering the minpath outputs again. This time for the superpathway of tetrathionate reduction. This pathway is important because it includes enzymes required to reduce sulfite to hydrogen sulfide. Note that sulfite acts as the terminal electron acceptor in this pathway, however, in a broader sense the term “sulfate reducing” refers to micro-organisms that can produce sulfide from a range of oxidised sulfur compounds.

``` bash
grep 'PWY-5360' *.ec.report
```

filtered outputs:

metabat.6.ec.report:path PWY-5360 any n/a naive 1 minpath 0 fam0 3 fam-found 1 name superpathway of tetrathionate reduction (Salmonella typhimurium)

\*not Salmonella typhimurium: this is a red herring and comes from the minpath database

Cross referencing the above results with the output from gtdbtk to see the taxonomy of bins containing this same pathway

``` bash
grep 'metabat.6' ../gtdbtk/out/gtdbtk.bac120.summary.tsv
```

#### Question 4.2:

How many bins contain the pathway PWY-5360?

1 bin

What family (in a taxonomic sense) do these bins belong to?

Arcobacteraceae

grep 'metabat.6' ../gtdbtk/out/gtdbtk.bac120.summary.tsv
